**PyTorch Tensor Basic Usage**
- Create Tensor
- Indexing, Joining(합치기), Slicing(일부 추출), 
- Inintialization
- Math Operations

**1. Create Tensor**

1) random numbers 

In [ ]:
#  새 노트에서 러타임 > GPU 로 다시 지정함. 
import torch

# torch.rand(sizes) ==> 0 ~ 1 사이의 실수값을 랜덤하게 발생함. 
# sizes : 1차원 갯수 or 2차원 핼렬 갯ㅅ 등으로 지정 
# 0 ~ 1 사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x

tensor([[0.0795, 0.4881, 0.0549],
        [0.3619, 0.1576, 0.1931]])

In [ ]:
#  torch.randn(sizes) ==> Z(0, 1)
# 평균이 0 이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
x = torch.randn(2, 3)
x

tensor([[ 0.4880, -0.6184, -0.5705],
        [ 0.8287,  1.6532,  0.9999]])

In [ ]:
# torch.randperm(n) ==> permutation of 0 ~ n 사이의 값을 랭덤하게 함
x = torch.randperm(5)
x

tensor([0, 3, 2, 4, 1])

**random 값을 가지는 tensor 생성시키는 함수들**

1. torch.rand() : 0 ~ 1 사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고
  기존의 텐서와 같은 구조를 만들때 사용
3. torch.randn() : 평균이 0이고 표쥰편차가 1인 가우시안 정규분호를 이용해 값 생성

4. torch.randn_like() : 사이즈를 튜플로 정하기 않고 
  기존의 텐서를 이용함

5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성. 
자료형은  torch.float32

6. torch.randint_likt() 
7. torch.randperm() : 주어진 범위 내에 정수를 랜덤하게 생성


**2) zeros, ones, arange**

In [ ]:
# torch.zeros(2, 3) ==> [[0,0,0], [0,0,0]]
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# torch.ones(2, 3) ==> [[1,1,1], [1,1,1,]]
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# torch.arange(start, end, step=1) ==> step : 값의 간격
x = torch.arange(0,3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

**3) Tensor Data Type**

In [ ]:
# torch.FloatTensor(size | list)
x = torch.FloatTensor(2, 3)
x

tensor([[6.3352e-35, 0.0000e+00, 1.0000e+00],
        [1.5000e+00, 2.0000e+00, 2.5000e+00]])

In [ ]:
x = torch.FloatTensor([12, 35])
x

tensor([12., 35.])

In [ ]:
# tensor.type_as(tensor_type)
# 기존 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

**4) Numpy to Tensor, Tensor to Numpy**

In [ ]:
import numpy as np

# torch.from_numpy(ndarray) ==> tensor로 변경해주는 함수
x1 = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array([1,2,3,4,5,6]))
print(x1)
x2 = torch.from_numpy(x1)
x2

[[1 2 3]
 [4 5 6]]


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# torch.numpy() ==> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

**5) Tensor on CPU & GPU**

In [ ]:
x = torch.FloatTensor([[1,2,3], [4,5,6]])
x

x_gpu = x.cuda()
x_gpu

x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**6) Tensor Size**

In [ ]:
# tensor객체.size() ==> 인덱스 값
x = torch.FloatTensor(10, 12, 3, 3) # start, end-1, row, col
x

x.size() # torch.Size([10, 12, 3, 3])
x.size()[:] # torch.Size([10, 12, 3, 3])

torch.Size([10, 12, 3, 3])

**2. Indexing, Slicing, Joining**

1) Indexing

In [ ]:
# torch.index_select(input, dim, index)
# dim == 행값, index == 열에 대한 인덱싱
x = torch.rand(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3]))

x, out

(tensor([[0.8537, 0.1433, 0.1228],
         [0.4021, 0.4451, 0.8234],
         [0.0916, 0.1219, 0.6607],
         [0.5449, 0.1915, 0.2527]]), tensor([[0.8537, 0.1433, 0.1228],
         [0.5449, 0.1915, 0.2527]]))

In [ ]:
# 파이썬의 인덱싱 사용 가능
x[:, 0] # 모든 행의 0열값들
x[0, :] # 0행의 모든 값
x[0:2, 0:2] # 0~1행, 0~1열까지의 값들

tensor([[0.8537, 0.1433],
        [0.4021, 0.4451]])

In [ ]:
# torch.masked_select(input, mask)
x = torch.randn(2, 3)
x
mask = torch.ByteTensor([[0,0,1], [0,1,0]])
out = torch.masked_select(x, mask)
out, x, mask

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1664.)
  """


(tensor([ 0.1902, -0.7319]), tensor([[ 0.9180, -1.5090,  0.1902],
         [-0.7767, -0.7319, -0.8323]]), tensor([[0, 0, 1],
         [0, 1, 0]], dtype=torch.uint8))

**2) Joining**

In [ ]:
# torch.cat(seq, dim=0)

x = torch.FloatTensor([[1,2,3], [4,5,6]])
y = torch.FloatTensor([[-1,-2,-3], [-4,-5,-6]])

z1 = torch.cat([x, y], dim= 0) # dim=0 이면 아래로 합쳐짐
z2 = torch.cat([x, y], dim=1) # dim=1 이면 오른쪽에 합쳐짐

x, y, z1, z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [ ]:
# torch.stack(sequence, dim=0) ==> 새로운 차원으로 추가
x_stack = torch.stack([x,x,x,x], dim=0) # (4, 2, 3) 모양
x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

**3) Slicing**


In [ ]:
# torch.chunk(tensor, chunk, dim=0)
x_1, x_2 = torch.chunk(z1, 2, dim=0) # dim=0 이면 행을 2개로 분할
y_1, y_2, y_3 = torch.chunk(z1, 3, dim=1) # dim=1 이면 열을 3개로 분할

z1, x_1, x_2, y_1, y_2, y_3

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]), tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]), tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [ ]:
# torch.split(tensor, split_size, dim=0)
x1, x2 = torch.split(z1, 2, dim=0)
y1 = torch.split(z1, 2, dim=1) # 3개 열을 2개로 분리한 경우

z1, x1, x2, y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), (tensor([[ 1.,  2.],
          [ 4.,  5.],
          [-1., -2.],
          [-4., -5.]]), tensor([[ 3.],
          [ 6.],
          [-3.],
          [-6.]])))

**4) squeezing**

In [ ]:
# torch.squeeze(input, dim=None) ==> 숫자가 1인 차원을 제거
x1 = torch.FloatTensor(10, 1, 3, 14)
# 차원의(dimention)의 개념
# 10: batch_size(데이터 한 묶음당 들어있는 데이터(x,y)쌍 갯수)
# 1 : channel size
# 3 : width image size
# 14 : height image size 

x2 = torch.squeeze(x1)
x1.size(), x2.size()

(torch.Size([10, 1, 3, 14]), torch.Size([10, 3, 14]))

In [ ]:
# torch.unsqueeze(input, dim=None) ==> 숫자가 1인 차원을 추가
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0)

x1.size(), x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

**3. Inintialization**

In [ ]:
import torch.nn.init as init
x1 = init.uniform(torch.FloatTensor(3,4), a=0, b=9)
# a에서 b까지의 값으로 초기화

x2 = init.normal(torch.FloatTensor(3,4), std=0.2) # 표준편차 0.2 적용 초기화
x3 = init.constant(torch.FloatTensor(3,4), 3.145) #지정된 상수 값으로 초기화

x1, x2, x3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  


(tensor([[0.5808, 7.1686, 7.7777, 8.7113],
         [0.6872, 0.2670, 6.5621, 0.6694],
         [6.0745, 5.2964, 5.4839, 7.7779]]),
 tensor([[ 0.0490,  0.1572, -0.1638,  0.3697],
         [-0.0674,  0.3451,  0.2131,  0.1998],
         [-0.0361,  0.0773,  0.0906, -0.1816]]),
 tensor([[3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450]]))

**4. Math Operations**

1) Arithmetic operations

In [ ]:
# torch.add()
x1 = torch.FloatTensor([[1,2,3,], [4,5,6,]])
x2 = torch.FloatTensor([[1,2,3,], [4,5,6,]])

x_add = torch.add(x1, x2)

x_add, x1, x2, x1+x2, x1-x2

(tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [ ]:
# torch.add() : broadcastion (숫자와의 연산)
x3 = torch.add(x1, 10) # 모든 행열에 10을 더한다.

x3, x1+10, x1-10

(tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[-9., -8., -7.],
         [-6., -5., -4.]]))

In [ ]:
# torch.mul() 곱하기
x3 = torch.mul(x1, x2)

x3, x1*x2

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]), tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [ ]:
x3 = torch.mul(x1, 10)
x3, x1*10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]), tensor([[10., 20., 30.],
         [40., 50., 60.]]))

In [ ]:
# torch.div() 나누기한 몫
x3 = torch.div(x1, 5)

x1, x3, x1/5

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]), tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]))

**2) Other Math Operations**

In [ ]:
# torch.pow(input, exponent)
x1 = torch.FloatTensor(3, 4)

x1, torch.pow(x1, 2), x1**2 

(tensor([[9.8410e+10, 0.0000e+00, 6.0000e-01, 8.0000e-01],
         [1.0000e+00, 1.2000e+00, 0.0000e+00, 2.3750e+00],
         [0.0000e+00, 2.3125e+00, 0.0000e+00, 2.2500e+00]]),
 tensor([[9.6846e+21, 0.0000e+00, 3.6000e-01, 6.4000e-01],
         [1.0000e+00, 1.4400e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]),
 tensor([[9.6846e+21, 0.0000e+00, 3.6000e-01, 6.4000e-01],
         [1.0000e+00, 1.4400e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]))

In [ ]:
# torch.exp(tensor, out=None) : exponential 연산
# y = e의 x 제곱 구할 때 사용
x1 = torch.FloatTensor(3,4)
out = torch.exp(x1)

x1, out

(tensor([[9.8407e+10, 0.0000e+00, 3.6000e-01, 6.4000e-01],
         [1.0000e+00, 1.4400e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]),
 tensor([[     inf,   1.0000,   1.4333,   1.8965],
         [  2.7183,   4.2207,   1.0000, 281.6387],
         [  1.0000, 210.1153,   1.0000, 157.9850]]))

In [ ]:
# torch.log(input, out=None) : 자연로그 계산
out = torch.log(x1)

x1, out

(tensor([[9.8407e+10, 0.0000e+00, 3.6000e-01, 6.4000e-01],
         [1.0000e+00, 1.4400e+00, 0.0000e+00, 5.6406e+00],
         [0.0000e+00, 5.3477e+00, 0.0000e+00, 5.0625e+00]]),
 tensor([[25.3124,    -inf, -1.0217, -0.4463],
         [ 0.0000,  0.3646,    -inf,  1.7300],
         [   -inf,  1.6767,    -inf,  1.6219]]))

**3) Matrix operations**

In [ ]:
# torch.mm(mat1, mat2) ==> matrix multiplication (행렬곱)
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)
out = torch.mm(x1, x2)

x1, x2, out


(tensor([[9.8405e+10, 0.0000e+00, 1.0217e+00, 4.4629e-01],
         [0.0000e+00, 3.6464e-01,        inf, 1.7300e+00],
         [       inf, 1.6767e+00,        inf, 1.6219e+00]]),
 tensor([[8.7697e+10, 0.0000e+00, 2.8372e-39, 1.3445e-39, 9.4367e-38],
         [3.5733e-43, 1.4125e-36, 7.3361e-39, 4.3506e-41, 1.8609e-42],
         [7.5232e-37, 1.4615e-39, 9.5840e-38, 0.0000e+00, 2.8358e-39],
         [1.3445e-39, 9.4367e-38, 3.5733e-43, 1.4125e-36, 7.3361e-39]]),
 tensor([[8.6298e+21, 4.3608e-38, 2.7920e-28, 1.3231e-28, 9.2862e-27],
         [       inf,        inf,        inf,        nan,        inf],
         [       inf,        nan,        inf,        nan,        inf]]))

In [ ]:
# torch.bmm(batch1, batch2) ==> batch 행렬곱 연산
# 맨 앞의 batch 는 차원을 유지하면서 뒤 요소들의 행렬곱 연산함

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)

out = torch.bmm(x1, x2)

out.size()

torch.Size([10, 3, 5])

In [ ]:
# torch.dot(tensor1, tensor2) : 백터의 내적을 구함
x1 = torch.FloatTensor([1,2,3,4])
x2 = torch.FloatTensor([2,3,4,5])

torch.dot(x1, x2)

tensor(40.)

In [ ]:
# torch.t(matrix) : transposed matrix (텐서의 전치연산)
# 행과 열을 서로 바꿈

x1 = torch.FloatTensor(3,4)

x1, x1.t()

(tensor([[9.8426e+10, 0.0000e+00, 5.1848e-44, 0.0000e+00],
         [       nan, 1.6914e-36, 3.0478e+32, 4.5925e+24],
         [1.7448e+22, 7.5878e+31, 1.8522e+28, 1.8057e+28]]),
 tensor([[9.8426e+10,        nan, 1.7448e+22],
         [0.0000e+00, 1.6914e-36, 7.5878e+31],
         [5.1848e-44, 3.0478e+32, 1.8522e+28],
         [0.0000e+00, 4.5925e+24, 1.8057e+28]]))

In [ ]:
# torch.transpose(input, dim_0, dim_1)
# 바꿀 차원을 2개를 지정함
# 텐서의 내부 차원간 바꾸기

x1 = torch.FloatTensor(10,3,4)

# 1차원과 2차원을 서로 바꿈
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1,2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [ ]:
# torch.eig(input, eigenvectors=False || True)
# 고유값(eigen_value), 또는 고유벡터(eigen_vector) 반환

x1 = torch.FloatTensor(4,4)
x1, torch.eig(x1, True)

(tensor([[ 9.8426e+10,  0.0000e+00,  2.3694e-38,  3.0478e+32],
         [ 4.5925e+24,  1.7448e+22,  7.5878e+31,  1.8522e+28],
         [ 1.8057e+28,  7.1901e+28,  6.2706e+22,  4.7428e+30],
         [ 8.6096e-42,  1.2979e-39, -2.3058e+38,  1.4013e-45]]),
 torch.return_types.eig(
 eigenvalues=tensor([[ 5.8031e+29,  3.3070e+34],
         [ 5.8031e+29, -3.3070e+34],
         [-1.1607e+30,  0.0000e+00],
         [-1.8998e+25,  0.0000e+00]]),
 eigenvectors=tensor([[-1.9844e-07, -9.2160e-03,  9.9999e-01,  9.6986e-01],
         [-3.2967e-07, -5.5986e-07,  5.6832e-05, -2.4364e-01],
         [-2.5168e-09, -1.4341e-04, -1.9243e-11, -1.0388e-14],
         [ 9.9996e-01,  0.0000e+00, -3.8081e-03,  5.2423e-08]])))